export * as productService from "./product.service.js";
export * as cartService from "./cart.service.js";
export * as checkoutService from "./checkout.service.js";
export * as orderServices from "./order.service.js";
export * as inventoryService from "./inventory.service.js";
export * as authServices from "./auth.service.js";
export * as tokenServices from "./token.service.js";
export * as categoryServices from "./category.service.js";
export * as colorServices from "./color.service.js";
export * as sizeServices from "./size.service.js";
export * as reviewServices from "./review.service.js";
export * as tagServices from "./tag.service.js";
export * as userServices from "./user.service.js";
export * as shippingService from './shipping.service.js';
export * as statsService from './stats.service.js'